### ISSUE TITLE
Clean error handling in assert

### ISSUE THREAD

**Issue by pikatoste** [pikatoste/test.sh#71]
# Description
The `assert` function sets error reporting handlers. This is not only useless, but also requires disabling further error reporting with an ugly and dangerous:

```
push_err_handler "pop_err_handler; print_stack_trace; touch $STACK_FILE"
```

This is currently ok because either the script quits after an assertion failure, or `subshell` is used, which reenables error reporting. It can manifest though if assert is used in teardown functions or executing: multiple `ignore $(assert_true false "first")`.

# Tasks
- [x] implementation
- documentation -- not required, internal change
- [x] test
  - [x] scenario 1: SUBSHELL=never|always
    * scenario: multiple `ignore $(assert_true false)
    * expected: each assert failure generates exactly one strack trace
  - [x] scenario 2: SUBSHELL=never|always
    * scenario: a test with an assertion failure an another assertion failure in `teardown_test`
    * expected: each assertion failure generates exactly one strack trace

# Requirements:
* - [x] Remove error handlers from `assert`

# DoD: Definition of Done criteria.
- [x] Tasks completed
- [x] Examples covered

**Comment by pikatoste** [comment]
# IMPORTANT UPDATE
It turns out that the special error handling was put in place so that assert error reports go before the `[test.sh] FAILED: test_01` test log outcome. **Maybe some code comments would have helped here**. Proposed implementation:

- [x] managed tests: change the failure notification handler from push to add. Actually improves current behaviour, as show by test_REENTER.sh: the notification was output _before_ the failure, with this change it goes _after_ the failure.
- [x] inline tests:no change necessary, notification is in exit handler
