### ISSUE TITLE
Location of temporary files

### ISSUE THREAD

**Issue by pikatoste** [pikatoste/test.sh#74]
# Description
Currently, temporary files are created in `/tmp`: test.sh doesn't work on platforms whith absent `/tmp`, such as android.

Related to this is the names of the temporary files:

* The log output pipe is created in an insecure manner: a name is chosen and then the file is created.
* The stack file is created as `stack-$$`, this is ok: little chance of clashing but somewhat impersonal.

Use envvar `TMPDIR` for temporary files if set, otherwise use `/tmp`.

Provide a common root for the two temporary files, try to fix the insecure creation and use mktemp for the stack file.

# Tasks
- [x] implementation
- [x] documentation: TMPDIR variable
- [x] test
  - [x] scenario 1
    * Execute test with modified TMPDIR
    * Check that temporary files are created there

# Requirements:
* - [x] Use TMPDIR or `/tmp` if unset
* - [x] Use mktemp with common root for temporary files

# DoD: Definition of Done criteria.
- [x] Tasks completed
- [x] Examples covered

# DoP: Definition of Perfect
- [x] Create the log file in a secure manner

**Comment by pikatoste** [comment]
# IMPORTANT UPDATE
A secure way to create a fifo with `mktemp` is to create a temporary directory instead of a file (`mktemp -d`) and then create the fifo in there. The stack file is created outside this folder because they have different cleanup requirements.

Now the 'common root' is the directory name and the fifo has a static name: `pipe`.

The stack file is called `<tmpdir>-stack`.

**Comment by pikatoste** [comment]
- [x] Also include test to check that all temporary files are removed after running all tests
