### ISSUE TITLE
Delete all uses and references to the subshell function

### ISSUE THREAD

**Issue by pikatoste** [pikatoste/test.sh#87]
- Verson originated: 0.1.0-SNAPSHOT-34caf27
- Version done: 0.1.0-SNAPSHOT-ce91592
----

# Description
The previous commit (34caf27c6f9288c61e6e5fe77e760a9720ae7aa9) implements `result_of`, an alternative and superior way of dealing with the use cases that `subshell` was developed for. This renders `subshell` obsolete and it's time to delete this function and its uses. Of course, this implies adapting tests and documentation.

With this change the complexity of the code, the usage (no more `source test.sh` restrictions) and the documentation is significantly reduced.

# Tasks
- [x] implementation
- [x] documentation
  - [x] function, configuration variables `SUBSHELL` and `REENTER`
  - [x] section on Subshells
  - [x] location of `source test`
  - [x] stack traces
  - [x] all other references: `assert_false`
- [x] test

# Requirements:
* [x] Delete function `subshell` and its uses in:
    - [x] code
    - [x] tests
    - [x] documentation
* [x] SUBSHELL_CMD, SUBSHELL, REENTER no longer necessary
    - [x] code
    - [x] tests
    - [x] documentation

Optional requirements:
* [x] Review the necessity for automatic export of variables. Implications in `run_test_script`. Try to change to not automatic export: remove `set -o allexport`.
  * Easy change. If a subtest expects a variable set in the parent, just export it. Breaks meaning of SUBSHELL_LOG_CONFIG=[reset|noreset], but it is still undocumented.
* [x] Review the possible simplifications in stack trace management
  * [x] the FOREIGN_STACK variable
  * [x] the necessity for the stack trace file, try to get rid of it
    * [x] use LOCAL_STACK array instead of file
    * The stack file is kept as a mechanism to communicate across subshells

**Comment by pikatoste** [comment]
Tiempo de ejecución de tests reducido en un 65% aprox.
