### ISSUE TITLE
Performance improvement: result_of

### ISSUE THREAD

**Issue by pikatoste** [pikatoste/test.sh#92]
- Verson originated: 0.1.0-SNAPSHOT-d48a0b0
- Version done: 0.1.0-SNAPSHOT-c998284
----

# Description
See parent issue #91.
The performance of test.sh is greatly influenced by the processes it executes, mainly external tools. Bash subshell environments are processes also. This issue deals with improving the `result_of` function::

* `result_of` creates a named pipe with `tee` attached to it on each call. It executes `mktemp`, `mkfifo`, `cat`, `tee` and `rm`. If we could redirect the evaluated command's output to the log pipeline, we would skip all three processes on each call to `result_of`. The scope of this improvement is all setup/teardown functions, all tests in managed mode, `assert_false`, all EXIT trap handlers andd explicit invocations of `result_of`.

# Tasks
- [x] implementation
- [x] test: all tests pass, no new tests required

# Requirements:
* [x] remove `mktemp`. Substitute by a counter
* [x] remove `cat`, `mkfifo` and `rm`. Use the log pipe instead
* [x] remove `tee`. Substitute:
  ```
  get_result "$(eval "$1" >&2)" "$2"
  ```
  for:
  ```
  get_result "$(eval "$1" | { tee "$pipe" >/dev/null || true; })" "$2"
  ```
  Explanation: `$(...)` redirects stdout, not stderr, which is still directed to the log pipe, so stdout is redirected there also. No need to use `$PIPE` which would introduce dleanup trouble.

**Comment by pikatoste** [comment]
# Benchmark
The results are not comparable because this change contains changes to the tests making two of them a bit slower after the improvement. Nevertheless, the results are vey good:
55,161s vs 36,274s: 1.52 times faster.

* Verson originated: 0.1.0-SNAPSHOT-d48a0b0
```
$ ( set -e; time for i in {1..10}; do make test >/dev/null; done; echo OK )
real	0m55,161s
user	0m48,470s
sys	0m11,346s
OK
```
* Version done: 0.1.0-SNAPSHOT-c998284
```
$ ( set -e; time for i in {1..10}; do make test >/dev/null; done; echo OK )
real	0m36,274s
user	0m28,703s
sys	0m6,598s
OK
```
