### ISSUE TITLE
Performance improvement: prune_path

### ISSUE THREAD

**Issue by pikatoste** [pikatoste/test.sh#93]
- Verson originated: 0.1.0-SNAPSHOT-d48a0b0
- Version base: 0.1.0-SNAPSHOT-c998284
- Version done: 0.1.0-SNAPSHOT-b549010
----

# Description
The performance of test.sh is greatly influenced by the processes it executes, mainly external tools. Bash subshell environments are processes also.  This issue deals with improving the `prune_path` function:

* `prune_path` executes `real_path`. Used in exception management code. Possible improvements: cache pruned paths in an associative array. The scope of this improvement is limited to errors. The cache is not reusable by different stack traces because each stack trace is captured in a subshell environment and any changes to the cache are local to that environment. It could be initialized at the start of the test with all known source files, though. The tests will benefit as they trigger many errors.

# Tasks
- [x] implementation
  - [x] use cache in `prune_path`
  - [x] set the result in a variable to avoid command substitution and the implied subshell environment 
  - [x] initialize the cache with the known files: the script, test.sh and any included file
  - [x] pass the cache to subtests in `run_test_script`
  - [x] reprocess the cache at the start of the cache initalization with the current PRUNE_PATH
  - [x] enable or disable initialization with configuration variable, default no initialization. Reprocessing is always done
- documentation: not required, this is an internal change
- [x] test
  - [x] scenario 1
    * `prune_path` is called with a path not in the cache
    * the path is stored in the cache
  - [x] scenario 2
    * `prune_path` is called with a path in the cache
    * the path is retrieved from the cache
  - [x] scenario 3
    * A subtest receives a preinitialized cache and a PRUNE_PATH different than the one with which the cache was initialized
    * the cache is reprocessed to apply the current PRUNE_PATH

**Comment by pikatoste** [comment]
# Implementation
Implemented cache in bash associative array. The cache is initialized at test start with the test script, test.sh and any included file. The parent cache is passed to subtests (i.e. run by `run_test_script`). If in a subtest, the cache is reprocessed with the current value of PRUNE_PATH.

The initialization of the cache is interesting because updates to the cache in `prune_path` are visible only in the current stack trace because of subshell environments. Initializing it in the main process makes it available to all stack traces.

This approach improves the benchmark of the base version by 8.65%. Not much, and this is **with the current tests**, which benefit the most because they produce many failures. In the event of no failures, the cache initialization will penalize.

Until a set of performance tests is developed (#95), the recommendation is to deactivate the cache initialization by default. test.sh tests can still benefit from the initialization by changing the default setting. This setting should remain an undocumented feature until more knowledge is gained.

# Benchmark
Current version:
```
$ ( make clean all prepare_test >/dev/null; set -e; time for i in {1..10}; do make test >/dev/null; done; echo OK )
real	0m33,135s
user	0m26,159s
sys	0m6,262s
OK
```
* Version base: 0.1.0-SNAPSHOT-c998284
```
$ ( set -e; time for i in {1..10}; do make test >/dev/null; done; echo OK )
real	0m36,274s
user	0m28,703s
sys	0m6,598s
OK
```
